[package]
name = "ucache"
version = "0.1.0"
edition = "2021"

[dependencies]
axerrno = "0.1"
axhal = { path = "../../arceos/modules/axhal", default-features = false }
log = "0.4"
spin = "0.9"
lru = "0.12"

[features]
default = []
