[package]
name = "unotify"
version = "0.1.0"
edition = "2021"

[dependencies]
axerrno = "0.1"
log = "0.4"
spin = "0.9"
alloc = { package = "axalloc", path = "../../arceos/modules/axalloc", default-features = false }

[features]
default = []
